# Generated by Django 4.1.6 on 2023-02-15 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_hired'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hired',
            options={'verbose_name_plural': 'Staff Hired'},
        ),
        migrations.AlterModelOptions(
            name='roles',
            options={'verbose_name_plural': 'Staff Roles'},
        ),
    ]
